# Bag of words analysis for GPT-4o generated text descriptions

In [23]:
import pandas as pd
from pathlib import Path

from AI_representation_bias_in_farming import module6_extract_pic_feature_words

# import the dataframe that records the 1 gram bag of words in all gpt-4o descriptions
gpt4o_description_file = Path("..") / "results" / "megadata" / "GPT4o_description_1_2gram_bag_of_words.csv"
gpt4o_description_1_2gram = pd.read_csv(gpt4o_description_file, header=0)

/var/folders/tt/5v8l17gn0fdbw73gwsn54j180000gn/T/ipykernel_62007/4127288516.py:8: DtypeWarning: Columns (2,5,10) have mixed types. Specify dtype option on import or set low_memory=False.
  gpt4o_description_1_2gram = pd.read_csv(gpt4o_description_file, header=0)

## Exploratory image analysis
The goal of this analysis is to see which word or phrases (2 words) are the key features that would describe an image of extensive versus intensive farm

[1] playground to seeing what context does each word show up in

In [24]:
# filter out the rows that certains words of interest, and print out in what sentences does the word shwo up
temp = gpt4o_description_1_2gram[gpt4o_description_1_2gram["farm_type"] == "dairy"]
count = temp['GPT4o_description'].str.contains('pastures', case=False, na=False)
filtered_df = temp[count].reset_index(drop=True)
print(filtered_df["GPT4o_description"][0])
filtered_df

The image depicts a vibrant, bustling farm scene. In the foreground, several cows are grazing in fenced pastures, with farmers tending to them. The cows are black and white, typical of dairy breeds, and are scattered across the lush green fields.

There are multiple barns in the background, painted in red with white trim, and a central barn that is white with a gray roof. These barns are surrounded by various farming equipment, including tractors and hay bales. A large silo is positioned near the barns, indicating grain storage.

The landscape extends into the distance with fields of crops and a river or stream running through the farmland. The sky is partly cloudy, suggesting a pleasant day. The overall scene is idyllic, capturing the essence of rural farm life with attention to detail in the activities and structures present.

,file,generation_type,country,farm_type,prompt,revised_prompt,model,size,quality,response_format,...,wraparound porch,yard,yellow,yellow ear,yellow flowers,young,young man,young pig,young pigs,young woman
0,dairy_farm_basic_2.png,basic,NaN,dairy,A dairy farm.,Picture a serene rural landscape under a clear...,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
1,dairy_farm_basic_5.png,basic,NaN,dairy,A dairy farm.,Imagine an engaging scene of a dairy farm. Pas...,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
2,dairy_farm_typical_3.png,typical,NaN,dairy,A typical dairy farm.,A detailed depiction of a typical dairy farm. ...,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
3,dairy_farm_reality_2.png,reality,NaN,dairy,Please create an image that accurately represe...,Generate a realistic image of a typical dairy ...,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
4,dairy_farm_reality_4.png,reality,NaN,dairy,Please create an image that accurately represe...,Visualize an image that displays a typical dai...,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,dairy_farm_typical_country_no_revise_New Zeala...,typical_country_no_revise,New Zealand,dairy,A typical dairy farm in New Zealand.I NEED to ...,A typical dairy farm in New Zealand.,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
347,dairy_farm_typical_country_no_revise_New Zeala...,typical_country_no_revise,New Zealand,dairy,A typical dairy farm in New Zealand.I NEED to ...,A typical dairy farm in New Zealand.,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
348,dairy_farm_typical_country_no_revise_New Zeala...,typical_country_no_revise,New Zealand,dairy,A typical dairy farm in New Zealand.I NEED to ...,A typical dairy farm in New Zealand,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
349,dairy_farm_typical_country_no_revise_New Zeala...,typical_country_no_revise,New Zealand,dairy,A typical dairy farm in New Zealand.I NEED to ...,A typical dairy farm in New Zealand,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0
350,dairy_farm_typical_country_no_revise_New Zeala...,typical_country_no_revise,New Zealand,dairy,A typical dairy farm in New Zealand.I NEED to ...,A typical dairy farm in New Zealand.,dall-e-3,1024x1024,standard,b64_json,...,0,0,0,0,0,0,0,0,0,0

[2] Exploratory : First list of interests
- I'll put all the images that contains the word of interest in its GPT-4o description text into a seperate folder.
- For example, all images that contain "grazing" will be placed into "results/cluster_eda/dairy/extensive/grazing"

In [ ]:
# list of words associated with extensive dairy
dairy_extensive = ["grazing", "graze", "grass", "pasture", "pastures"]
dairy_intensive = ["automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]
pig_extensive = ["mud", "muddy", "soil", "dirt", "outdoor", "rural", "green", "grazing", "pasture", "pastures", "graze", "grass", "straw"]
pig_intensive = ["floor", "automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]

- Warning: the code cell below takes a long time to run (~ 30 minutes), please don't run again, as it's time and resource consuming.

In [28]:
# Set up base paths
model = "dall-e-3"
source_base = Path("..") / "results"
dest_base = Path("..") / "results" / "cluster_eda"
# Process pig extensive
pig_extensive = ["straw"]
module6_extract_pic_feature_words.process_farm_images(
    gpt4o_description_1_2gram,
    "pig",
    "extensive",
    pig_extensive,
    source_base,
    dest_base,
    model,
)

In [ ]:
# Set up base paths
model = "dall-e-3"
source_base = Path("..") / "results"
dest_base = Path("..") / "results" / "cluster_eda"

# Process dairy extensive
module6_extract_pic_feature_words.process_farm_images(
    gpt4o_description_1_2gram,
    "dairy",
    "extensive",
    dairy_extensive,
    source_base,
    dest_base,
    model,
)

# Process dairy intensive
module6_extract_pic_feature_words.process_farm_images(
    gpt4o_description_1_2gram,
    "dairy",
    "intensive",
    dairy_intensive,
    source_base,
    dest_base,
    model,
)

# Process pig extensive
module6_extract_pic_feature_words.process_farm_images(
    gpt4o_description_1_2gram,
    "pig",
    "extensive",
    pig_extensive,
    source_base,
    dest_base,
    model,
)

# Process pig intensive
module6_extract_pic_feature_words.process_farm_images(
    gpt4o_description_1_2gram,
    "pig",
    "intensive",
    pig_intensive,
    source_base,
    dest_base,
    model,
)

Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_1.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_2.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_4.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_5.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_7.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_8.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_9.png
Source file not found: results/dall-e-3-images/basic/dairy_farm_basic_10.png
Source file not found: results/dall-e-3-images/basic_no_revise/dairy_farm_basic_no_revise_2.png
Source file not found: results/dall-e-3-images/basic_no_revise/dairy_farm_basic_no_revise_4.png
Source file not found: results/dall-e-3-images/basic_no_revise/dairy_farm_basic_no_revise_5.png
Source file not found: results/dall-e-3-images/basic_no_revise/dairy_farm_basic_no_revise_6.png
Source file not found: results/dall-e-3-images/basic_no_revise/dairy_farm_basic_no_revise_9.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_1.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_2.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_3.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_4.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_5.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_6.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_7.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_8.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_9.png
Source file not found: results/dall-e-3-images/typical/dairy_farm_typical_10.png
Source file not found: results/dall-e-3-images/typical_no_revise/dairy_farm_typical_no_revise_10.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_1.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_2.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_3.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_4.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_5.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_6.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_7.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_8.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_9.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_10.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_1.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_2.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_3.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_5.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_6.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_7.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_8.png
Source file not found: results/dall-e-3-images/reality_no_revise/dairy_farm_reality_no_revise_10.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_2.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_3.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_4.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_5.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_7.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_8.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_9.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_the United States_10.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_3.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_4.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_5.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_6.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_7.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_8.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_Germany_10.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_1.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_2.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_3.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_4.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_6.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_9.png
Source file not found: results/dall-e-3-images/reality_country/dairy_farm_reality_country_New Zealand_10.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_1.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_2.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_3.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_4.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_5.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_6.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_7.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_8.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_9.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_the United States_10.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_Germany_1.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_Germany_3.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_Germany_6.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_Germany_7.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_1.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_2.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_3.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_5.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_7.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_8.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_9.png
Source file not found: results/dall-e-3-images/reality_country_no_revise/dairy_farm_reality_country_no_revise_New Zealand_10.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_1.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_3.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_4.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_5.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_6.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_8.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_9.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_the United States_10.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_Germany_1.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_Germany_2.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_Germany_4.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_Germany_5.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_Germany_7.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_New Zealand_1.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_New Zealand_2.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_New Zealand_5.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_New Zealand_8.png
Source file not found: results/dall-e-3-images/basic_country/dairy_farm_basic_country_New Zealand_9.png
Source file not found: results/dall-e-3-images/basic_country_no_revise/dairy_farm_basic_country_no_revise_New Zealand_1.png
Source file not found: results/dall-e-3-images/basic_country_no_revise/dairy_farm_basic_country_no_revise_New Zealand_7.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_1.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_2.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_3.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_4.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_5.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_6.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_7.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_8.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_9.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_the United States_10.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_1.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_3.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_4.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_5.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_6.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_8.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_9.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_Germany_10.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_1.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_2.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_3.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_4.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_5.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_7.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_8.png
Source file not found: results/dall-e-3-images/typical_country/dairy_farm_typical_country_New Zealand_10.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_the United States_3.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_the United States_7.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_Germany_4.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_Germany_9.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_3.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_4.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_5.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_6.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_8.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_9.png
Source file not found: results/dall-e-3-images/typical_country_no_revise/dairy_farm_typical_country_no_revise_New Zealand_10.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_11.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_12.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_13.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_14.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_15.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_18.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_19.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_20.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_21.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_22.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_24.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_26.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_27.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_28.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_29.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_30.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_31.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_32.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_33.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_35.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_36.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_37.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_38.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_39.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_40.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_41.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_42.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_43.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_44.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_45.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_47.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_48.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_49.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_50.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_51.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_52.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_53.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_54.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_55.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_57.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_58.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_59.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_60.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_62.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_63.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_64.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_65.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_66.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_67.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_68.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_69.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_70.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_71.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_72.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_73.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_74.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_75.png
Source file not found: results/dall-e-3-images/reality/dairy_farm_reality_76.png

[2] Exploratory : Second list of interests (refined based on the first)

In [ ]:
# list of words associated with extensive dairy
#dairy_extensive = ["grazing", "graze", "grass", "pasture", "pastures"]
#dairy_intensive = ["automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]
#pig_extensive = ["mud", "muddy", "soil", "dirt", "outdoor", "rural", "green", "grazing"]
#pig_intensive = ["floor", "automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]

dairy_extensive = ["grazing", "graze", "pasture", "pastures"]
dairy_extensive_negative_list = ["ceiling"]
dairy_intensive = ["ceiling", "metal railing", "metal railings", "barn spacious", "interior", "large windows", "automtaed", "modern"]
dairy_intensive_negative_list = ["grazing", "graze", "pasture", "pastures"]
pig_extensive = ["grazing", "graze", "pasture", "pastures", "grass", "soil", "green",           "mud", "muddy", "straw", "dirt", "outdoor", "rural"]
pig_extensive_negative_list = ["ceiling"]
pig_intensive = ["floor", "ceiling", "interior", "automated", "metal railing", "metal railings", "barn spacious", "large windows"]
pig_intensive_negative_list = ["grazing", "graze", "pasture", "pastures", "grass", "soil", "outdoor"]
intensive_extensive_summary = (
    module6_extract_pic_feature_words.intensive_extensive_calculation(
        gpt4o_description_1_2gram,
        dairy_extensive,
        dairy_intensive,
        pig_extensive,
        pig_intensive,
    )
)
final = intensive_extensive_summary[(intensive_extensive_summary["farm_type"] == "dairy")][["generation_type", "country", "farm_type", "model", "exten_pct"]]

In [40]:
row = gpt4o_description_1_2gram[gpt4o_description_1_2gram["file"] == "pig_farm_basic_country_Australia_50.png"]
columns_with_ones = row.columns[row.iloc[0] == 1].tolist()

print(columns_with_ones)

['adding', 'adding serene', 'age', 'appear', 'appear content', 'atmosphere scene', 'background features', 'bale', 'barn', 'barn corrugated', 'barn large', 'barn pitched', 'captures', 'casting', 'casting long', 'clear', 'content', 'corrugated', 'corrugated metal', 'depicts rural', 'distance', 'distance sky', 'doors', 'doors revealing', 'enclosing', 'enclosing area', 'environment', 'environment pigs', 'extending', 'extending distance', 'farm life', 'features', 'features rolling', 'feed', 'feed background', 'fence', 'fence enclosing', 'foreground group', 'gathered', 'gathered muddy', 'glimpse', 'golden', 'golden light', 'grass', 'green', 'green grass', 'group', 'group pigs', 'hay', 'hay bale', 'hills', 'idyllic', 'idyllic farm', 'image captures', 'interior', 'large', 'large hay', 'large rustic', 'left', 'left barn', 'life', 'light', 'light casting', 'long', 'long shadows', 'lush', 'lush green', 'metal', 'mud', 'muddy', 'muddy area', 'open', 'open doors', 'overall image', 'pastoral', 'pastoral atmosphere', 'peaceful', 'peaceful idyllic', 'pigs gathered', 'pigs large', 'pigs various', 'pitched', 'pitched roof', 'revealing', 'rolling', 'rolling hills', 'roof', 'roof open', 'rural', 'rural farm', 'rustic', 'rustic barn', 'scene overall', 'scene sunrise', 'serene', 'serene pastoral', 'shadows', 'showing', 'showing signs', 'signs', 'sizes', 'sky', 'sky clear', 'suggesting farm', 'sunrise', 'sunrise sunset', 'sunset', 'sunset warm', 'various', 'various sizes', 'walking', 'walking pigs', 'wallowing', 'wallowing mud', 'warm', 'warm golden', 'wood', 'wooden', 'wooden fence']

In [19]:
dairy_extensive = ["grazing", "graze", "pasture", "pastures", "grass"]
dairy_intensive = ["automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]
pig_extensive = ["mud", "muddy", "soil", "dirt", "outdoor", "rural", "green", "grazing"]
pig_intensive = ["floor", "automated", "ceiling", "interior", "machinery", "machine", "machines", "modern", "metal", "roofed", "metal railing", "metal railings", "large windows", "barn spacious"]

intensive_extensive_summary = (
    module6_extract_pic_feature_words.intensive_extensive_calculation(
        gpt4o_description_1_2gram,
        dairy_extensive,
        dairy_intensive,
        pig_extensive,
        pig_intensive,
    )
)
final2 = intensive_extensive_summary[(intensive_extensive_summary["farm_type"] == "dairy")][["generation_type", "country", "farm_type", "model", "exten_pct"]]

In [20]:
test = final2
test["dif"] = final2["exten_pct"] - final["exten_pct"]
test

,generation_type,country,farm_type,model,exten_pct,dif
0,basic,NaN,dairy,dall-e-3,0.98,0.03
2,basic_no_revise,NaN,dairy,dall-e-3,0.28,0.03
4,typical,NaN,dairy,dall-e-3,0.99,0.00
6,typical_no_revise,NaN,dairy,dall-e-3,0.28,0.01
8,reality,NaN,dairy,dall-e-3,0.97,0.00
10,reality_no_revise,NaN,dairy,dall-e-3,0.86,0.01
12,reality_country,the United States,dairy,dall-e-3,0.92,0.01
13,reality_country,Germany,dairy,dall-e-3,0.96,0.01
14,reality_country,New Zealand,dairy,dall-e-3,0.98,0.04
18,reality_country_no_revise,the United States,dairy,dall-e-3,0.66,0.04
19,reality_country_no_revise,Germany,dairy,dall-e-3,0.75,0.01
20,reality_country_no_revise,New Zealand,dairy,dall-e-3,0.93,0.06
24,basic_country,the United States,dairy,dall-e-3,0.97,0.04
25,basic_country,Germany,dairy,dall-e-3,0.98,0.05
26,basic_country,New Zealand,dairy,dall-e-3,0.98,0.03
30,basic_country_no_revise,the United States,dairy,dall-e-3,0.02,0.00
31,basic_country_no_revise,Germany,dairy,dall-e-3,0.05,0.00
32,basic_country_no_revise,New Zealand,dairy,dall-e-3,0.31,0.06
36,typical_country,the United States,dairy,dall-e-3,1.00,0.01
37,typical_country,Germany,dairy,dall-e-3,1.00,0.01
38,typical_country,New Zealand,dairy,dall-e-3,0.99,0.03
42,typical_country_no_revise,the United States,dairy,dall-e-3,0.13,0.01
43,typical_country_no_revise,Germany,dairy,dall-e-3,0.26,0.09
44,typical_country_no_revise,New Zealand,dairy,dall-e-3,0.59,0.10
48,reality,NaN,dairy,sd3.5-large,0.70,0.00
50,reality_no_revise,NaN,dairy,sd3.5-large,1.00,0.40
52,reality_country,the United States,dairy,sd3.5-large,0.50,0.00
53,reality_country,Germany,dairy,sd3.5-large,0.50,0.00
54,reality_country,New Zealand,dairy,sd3.5-large,1.00,0.10
58,reality_country_no_revise,the United States,dairy,sd3.5-large,1.00,0.10
59,reality_country_no_revise,Germany,dairy,sd3.5-large,0.90,0.10
60,reality_country_no_revise,New Zealand,dairy,sd3.5-large,1.00,0.00
64,basic,NaN,dairy,sd3.5-large,0.90,0.10
66,basic_no_revise,NaN,dairy,sd3.5-large,0.90,0.20
68,basic_country,the United States,dairy,sd3.5-large,0.90,0.00
69,basic_country,Germany,dairy,sd3.5-large,0.60,0.00
70,basic_country,New Zealand,dairy,sd3.5-large,1.00,0.10
74,basic_country_no_revise,the United States,dairy,sd3.5-large,0.70,0.00
75,basic_country_no_revise,Germany,dairy,sd3.5-large,0.80,0.20
76,basic_country_no_revise,New Zealand,dairy,sd3.5-large,0.90,0.00
80,typical,NaN,dairy,sd3.5-large,0.70,0.00
82,typical_no_revise,NaN,dairy,sd3.5-large,1.00,0.00
84,typical_country,the United States,dairy,sd3.5-large,1.00,0.20
85,typical_country,Germany,dairy,sd3.5-large,1.00,0.00
86,typical_country,New Zealand,dairy,sd3.5-large,0.90,0.00
90,typical_country_no_revise,the United States,dairy,sd3.5-large,0.90,0.10
91,typical_country_no_revise,Germany,dairy,sd3.5-large,0.90,0.10
92,typical_country_no_revise,New Zealand,dairy,sd3.5-large,1.00,0.00

In [16]:
test = grazing_graze_pasture_pastures
test["dif"] = grazing_graze_pasture_pastures["exten_pct"] - grazing_graze["exten_pct"]
test

,generation_type,country,farm_type,model,exten_pct,dif
0,basic,NaN,dairy,dall-e-3,0.95,0.03
2,basic_no_revise,NaN,dairy,dall-e-3,0.25,0.00
4,typical,NaN,dairy,dall-e-3,0.99,0.00
6,typical_no_revise,NaN,dairy,dall-e-3,0.27,0.00
8,reality,NaN,dairy,dall-e-3,0.97,0.04
10,reality_no_revise,NaN,dairy,dall-e-3,0.85,0.01
12,reality_country,the United States,dairy,dall-e-3,0.91,0.01
13,reality_country,Germany,dairy,dall-e-3,0.95,0.01
14,reality_country,New Zealand,dairy,dall-e-3,0.94,0.07
18,reality_country_no_revise,the United States,dairy,dall-e-3,0.62,0.01
19,reality_country_no_revise,Germany,dairy,dall-e-3,0.74,0.03
20,reality_country_no_revise,New Zealand,dairy,dall-e-3,0.87,0.03
24,basic_country,the United States,dairy,dall-e-3,0.93,0.02
25,basic_country,Germany,dairy,dall-e-3,0.93,0.05
26,basic_country,New Zealand,dairy,dall-e-3,0.95,0.08
30,basic_country_no_revise,the United States,dairy,dall-e-3,0.02,0.00
31,basic_country_no_revise,Germany,dairy,dall-e-3,0.05,0.02
32,basic_country_no_revise,New Zealand,dairy,dall-e-3,0.25,0.03
36,typical_country,the United States,dairy,dall-e-3,0.99,0.00
37,typical_country,Germany,dairy,dall-e-3,0.99,0.05
38,typical_country,New Zealand,dairy,dall-e-3,0.96,0.04
42,typical_country_no_revise,the United States,dairy,dall-e-3,0.12,0.01
43,typical_country_no_revise,Germany,dairy,dall-e-3,0.17,0.00
44,typical_country_no_revise,New Zealand,dairy,dall-e-3,0.49,0.05
48,reality,NaN,dairy,sd3.5-large,0.70,0.30
50,reality_no_revise,NaN,dairy,sd3.5-large,0.60,0.10
52,reality_country,the United States,dairy,sd3.5-large,0.50,0.10
53,reality_country,Germany,dairy,sd3.5-large,0.50,0.00
54,reality_country,New Zealand,dairy,sd3.5-large,0.90,0.00
58,reality_country_no_revise,the United States,dairy,sd3.5-large,0.90,0.20
59,reality_country_no_revise,Germany,dairy,sd3.5-large,0.80,0.20
60,reality_country_no_revise,New Zealand,dairy,sd3.5-large,1.00,0.10
64,basic,NaN,dairy,sd3.5-large,0.80,0.20
66,basic_no_revise,NaN,dairy,sd3.5-large,0.70,0.20
68,basic_country,the United States,dairy,sd3.5-large,0.90,0.10
69,basic_country,Germany,dairy,sd3.5-large,0.60,0.00
70,basic_country,New Zealand,dairy,sd3.5-large,0.90,0.00
74,basic_country_no_revise,the United States,dairy,sd3.5-large,0.70,0.20
75,basic_country_no_revise,Germany,dairy,sd3.5-large,0.60,0.20
76,basic_country_no_revise,New Zealand,dairy,sd3.5-large,0.90,0.10
80,typical,NaN,dairy,sd3.5-large,0.70,0.20
82,typical_no_revise,NaN,dairy,sd3.5-large,1.00,0.30
84,typical_country,the United States,dairy,sd3.5-large,0.80,0.10
85,typical_country,Germany,dairy,sd3.5-large,1.00,0.10
86,typical_country,New Zealand,dairy,sd3.5-large,0.90,0.00
90,typical_country_no_revise,the United States,dairy,sd3.5-large,0.80,0.20
91,typical_country_no_revise,Germany,dairy,sd3.5-large,0.80,0.10
92,typical_country_no_revise,New Zealand,dairy,sd3.5-large,1.00,0.00